### PR TITLE
Fix for devDependencies

### PR DESCRIPTION
**Pull request by boulosdib**
This fix will now show either or both dependencies and devDependencies.
Previously, if there were no dependencies, the devDependencies were not even processed.

### CODE REVIEW

**Comment by knownasilya** [comment]
:+1:

**Comment by knownasilya** [comment]
:+1:

**Comment by zeke** [comment]
Hey sorry I missed this. I've updated the extension and this should be fixed.

**Comment by boulosdib** [comment]
Awesome, thank you.

**Pull request closed without merging**
