### PR TITLE
Converted to plain Web Extension

### LINKED ISSUE #6: Browser warning
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### LINKED ISSUE #8: Limit extension to github.com
This is currently being applied to all websites, generating [console errors](#6) and appending `crossrider_data_store_temp` attributes on `body` everywhere. It should be limited to the github.com domain only.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #8 
Fixes #6

This includes some support for Firefox as a web extension, but there's an issue with GitHub's CSP. It can be installed in Firefox in `about:debugging`

### CODE REVIEW

**Comment by zeke** [comment]
This is awesome. Gonna give it a spin tonight or tomorrow.

**Comment by bfred-it** [comment]
It works on Firefox now too :)

**Comment by zeke** [comment]
🔥 :fox:

**Comment by zeke** [comment]
Hey sorry this is taking so long I'm chipping away at it. Working my way through https://github.com/DrewML/chrome-webstore-upload-cli/issues/7#issuecomment-230198684 thanks to @DrewML!

**Comment by zeke** [comment]
Thanks for the bump!

**Comment by bfred-it** [comment]
Can this be pulled while the auto-deployment gets resolved?

**Comment by zeke** [comment]
Oldest PR evar. 🙈

**Comment by bfred-it** [comment]
It happens :D

**Comment by bfred-it** [comment]
Autodeployment is in! That only took 4 months :D

**Comment by zeke** [comment]
📆 📆 📆 📆 

Happy new year!

**Pull request merged**
