### PR TITLE
show dependency version info

### PR DESCRIPTION
**Pull request by dotcypress**
screen shot 2016-09-22 at 6 25 47 pm

### CODE REVIEW

**Comment by bfred-it** [comment]
Not crazy about how it looks, perhaps this should be `<small>(^2.2.0)</small>` instead of `<strong>^2.2.0</strong>`

**Comment by dotcypress** [comment]
@bfred-it what about this style?
screen shot 2016-09-23 at 8 26 26 am

**Comment by bfred-it** [comment]
I had tried it and didn't like it, but seeing it again actually it's not bad at all. So LGTM

**Comment by zeke** [comment]
Both are fine with me, but I think I prefer the newer `code` style.

**Comment by dotcypress** [comment]
@zeke sweet! 👍 
Changes already in PR.

**Comment by zeke** [comment]
Now that I'm seeing this in the wild, I don't really feel like seeing the semver range is actually that helpful. The name and description are what really matter. If I want to know the package versions used by a given project, the package.json file is not far away. 

I think the version should be removed, or at the very least removed to the end of the description. Anyone else feeling that?

screen shot 2017-01-09 at 9 32 51 pm

**Comment by bfred-it** [comment]
You're not wrong. I wouldn't mind implementing [options](https://github.com/bfred-it/webext-options-sync)

**Comment by zeke** [comment]
@bfred-it are there other things you think should be configurable?

I would prefer to avoid adding user preferences if possible, just to keep things simple.

**Comment by bfred-it** [comment]
I can't think of any at the moment. The UI would be almost non-existent though:

prototype

**Comment by zeke** [comment]
My vote: drop the version; add preferences some other day if we ever end up needing them.

**Pull request merged**
