### PR TITLE
Match GitHub's style

### PR DESCRIPTION
**Pull request by bfred-it**
I tested this in Chrome

### CODE REVIEW

**Comment by zeke** [comment]
Nice!

**Comment by bfred-it** [comment]
I'm still seeing the old style on Chrome. Does this need to be updated on Crossrider

**Comment by zeke** [comment]
Hey apologies for the slowness.

I have a dev version of it running, and the font looks a bit chunky to me:

screen shot 2016-06-07 at 5 02 38 pm

I think a smaller font size like that of the file listing would be better. I hesitated because I didn't want to play css whack-a-mole. You want to take a crack at it?

**Pull request merged**
