### PR TITLE
Add support for private repos

### PR DESCRIPTION
**Pull request by DrewML**
Thanks for the excellent extension @zeke and @bfred-it!

Took a stab at adding support for private repos, since I use them on a day-to-day basis. I initially was going to make a request to `https://github.com/user/repo/raw/master/package.json`, but it 301s to a host that isn't allowed by the content security policy on the page.

I needed to move the request from the background page to the content script, because the current session cookie needs to be sent with the request for auth w/ private repositories.

### CODE REVIEW

**Comment by bfred-it** [comment]
The background fetch was added for Firefox but it looks like this works. LGTM. @zeke?

**Comment by bfred-it** [comment]
I saw that `https://github.com/user/repo/raw/master/package.json` redirects to `raw.githubusercontent.com` anyway, the old url. Does `https://raw.githubusercontent.com/user/repo/master/package.json` work for private repos? Redirects take longer, it's best if we can avoid them

On a related note, do you know of a path to get the default branch rather than `master`?

**Comment by DrewML** [comment]
> Does https://raw.githubusercontent.com/user/repo/master/package.json work for private repos?

It _does_ technically work, but the content security policy GitHub has in place has a whitelist of domains you can make requests to, and `githubusercontent.com` isn't in there, so the promise will reject. So it worked before because requests from the background page aren't subject to the CSP, but then you can't send the auth info needed for private repos.

> On a related note, do you know of a path to get the default branch rather than master

I don't 😞. Having said that, is the preference to always show deps for the default branch, vs showing  the deps for the branch currently being viewed?

**Comment by zeke** [comment]
Thanks @DrewML! It would be nice to support this.

> content security policy GitHub has in place has a whitelist of domains you can make requests to, and githubusercontent.com isn't in there.

☝️  This is probably intentional to keep people from treating that domain as a CDN, but I can ping the GitHub security team and see about it. cc @tmaher

> is the preference to always show deps for the default branch, vs showing the deps for the branch currently being viewed?

☝️  I would think defaulting to the currently-viewed branch would make the most sense.

If @bfred-it is good with landing this, we should then remove [background-fetch.js](https://github.com/zeke/npm-hub/blob/96d8688cd024941d7e6fc8c9bb506a03ebce73a7/extension/background-fetch.js). Note also that the existing `backgroundFetch` method is used in two places.

Is there a CI service for browser extensions? Would be nice to get some tests in place for this project.

**Comment by bfred-it** [comment]
Sounds good. If GH ends up adding raw.githubusercontent.com to their CSP we can go back

**Comment by DrewML** [comment]
> Is there a CI service for browser extensions? Would be nice to get some tests in place for this project.

You can use the `ChromeDriver` w/ `SauceLabs` to load up an extension. Can't say I've tried it before, though. Would probably need to make sure we have an example repo that never gets touched or the tests could be flakey.

**Comment by bfred-it** [comment]
@zeke I think background-fetch is still still required to access the npm registry

**Comment by bfred-it** [comment]
@zeke are we good to merge this?

**Comment by zeke** [comment]
🚢

**Comment by DrewML** [comment]
🎉 Thanks guys!

**Pull request merged**
